<?php
	$aSQLCon = array (
		"tag"=>array(
			"tableName"=>"tag",
			"element"=>array(
				"id"=>array(
					"type"=>"int",
					"rule"=>"",
					"rType"=>"list"
				),
				"tag_name"=>array(
					"type"=>"varchar",
					"rule"=>"",
					"rType"=>"string"
				),
				"search_times"=>array(
					"type"=>"int",
					"rule"=>"",
					"rType"=>"string"
				),
				"use_times"=>array(
					"type"=>"int",
					"rule"=>"",
					"rType"=>"string"
				),
				"add_time"=>array(
					"type"=>"int",
					"rule"=>"",
					"rType"=>"string"
				),
				"tag_id"=>array(
					"type"=>"varchar",
					"rule"=>"",
					"rType"=>"string"
				),
				"tag_value"=>array(
					"type"=>"varchar",
					"rule"=>"",
					"rType"=>"string"
				),
				"add_user_id"=>array(
					"type"=>"int",
					"rule"=>"",
					"rType"=>"string"
				),
			),
			"priKey"=>"id",
			"abre"=>"tag"
		),
	);
?>

